name: image-build
on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/image-build.yaml"

jobs:
  image-build:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: pratikimprowise/ghar-image
          tags: |
            type=raw,value={{branch}}-{{sha}}-{{date 'X'}}
            type=raw,value=latest

      - name: Docker login
        id: docker-login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Image Build
        run: |
          tags='${{ steps.meta.outputs.tags }}'
          export IFS=$'\n'
          tmp_tag="${{ github.run_id }}-${{ github.run_number }}-${{ github.sha }}"
          docker build -t $tmp_tag .
          for tag in $tags; do docker tag $tmp_tag $tag; done

      - name: Image Push
        run: |
          tags='${{ steps.meta.outputs.tags }}'
          export IFS=$'\n'
          for tag in $tags; do docker push $tag; done

      - name: Post Docker login
        if: ${{ steps.docker-login.outcome == 'success' }}
        run: docker logout

      # - name: Slack Notification
      #   uses: lazy-actions/slatify@master
      #   continue-on-error: true
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     job_name: "*Apricot API CI*"
      #     channel: "#apricot2"
      #     url: ${{ secrets.SLACK_WEBHOOK }}
      #     commit: true
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Docker Hub Status
        if: failure() || cancelled()
        uses: crazy-max/ghaction-docker-status@v1
        with:
          overall_threshold: degraded_performance
